### ISSUE TITLE
TokenList生成token并加logo与价格

### ISSUE THREAD

**Issue by FrederickKang** [ACY-Labs/acy-dex-interface#11]
- [x] Drag and drop this card to the new column
- [x] Search for and add issues or PRs to your project
- [x] Manage automation on columns
- [x] [Archive a card]

**Comment by FrederickKang** [comment]
![image](https://user-images.githubusercontent.com/87684304/134483861-e6d44b8a-d11c-4577-a5df-4f37e16c947c.png)
这个修改一下

**Comment by FrederickKang** [comment]
@chwizdo Anderson，这一块区域的Token list是你在负责，但是要祖斌参与才行，因为他要生成大量的测试用Token。

**Comment by ngjuping** [comment]
完成了，请找我拿这个测试账号的助记词
